"""Допустимые типы операторов и узлов AST для валидации SQL."""

from pglast.ast import (
    A_ArrayExpr,
    A_Const,
    A_Expr,
    A_Indices,
    A_Indirection,
    A_Star,
    Alias,
    BitString,
    Boolean,
    BooleanTest,
    BoolExpr,
    CaseExpr,
    CaseWhen,
    ClosePortalStmt,
    CoalesceExpr,
    CollateClause,
    ColumnRef,
    CommonTableExpr,
    CreateExtensionStmt,
    DeallocateStmt,
    DeclareCursorStmt,
    DefElem,
    DeleteStmt,
    ExplainStmt,
    FetchStmt,
    Float,
    FromExpr,
    FuncCall,
    GroupingFunc,
    GroupingSet,
    InsertStmt,
    Integer,
    JoinExpr,
    MinMaxExpr,
    NamedArgExpr,
    NullTest,
    ParamRef,
    PrepareStmt,
    RangeFunction,
    RangeSubselect,
    RangeTableFunc,
    RangeTableFuncCol,
    RangeTableSample,
    RangeVar,
    RawStmt,
    ResTarget,
    RowCompareExpr,
    RowExpr,
    ScalarArrayOpExpr,
    SelectStmt,
    SortBy,
    SortGroupClause,
    SQLValueFunction,
    String,
    SubLink,
    TableFunc,
    TableSampleClause,
    TargetEntry,
    TypeCast,
    TypeName,
    UpdateStmt,
    VariableShowStmt,
    WindowClause,
    WindowDef,
    WindowFunc,
    WithClause,
)


ALLOWED_STMT_TYPES: set[type] = {
    SelectStmt,
    ExplainStmt,
    VariableShowStmt,
    PrepareStmt,
    DeallocateStmt,
    DeclareCursorStmt,
    ClosePortalStmt,
    FetchStmt,
}

ALLOWED_NODE_TYPES: set[type] = ALLOWED_STMT_TYPES | {
    ResTarget,
    ColumnRef,
    A_Star,
    A_Const,
    A_Expr,
    BoolExpr,
    BooleanTest,
    NullTest,
    RangeVar,
    JoinExpr,
    FromExpr,
    WithClause,
    CommonTableExpr,
    SubLink,
    MinMaxExpr,
    RowExpr,
    DefElem,
    SortBy,
    SortGroupClause,
    Integer,
    Float,
    String,
    BitString,
    Boolean,
    RawStmt,
    ParamRef,
    SQLValueFunction,
    FuncCall,
    TypeCast,
    TypeName,
    Alias,
    CaseExpr,
    CaseWhen,
    RangeSubselect,
    CoalesceExpr,
    NamedArgExpr,
    RangeFunction,
    A_ArrayExpr,
    WindowFunc,
    WindowDef,
    WindowClause,
    TableFunc,
    RangeTableFunc,
    RangeTableFuncCol,
    A_Indirection,
    A_Indices,
    GroupingSet,
    GroupingFunc,
    RangeTableSample,
    TableSampleClause,
    RowCompareExpr,
    CollateClause,
    TargetEntry,
    ScalarArrayOpExpr,
}

# Statements that are allowed only when read_only=False. CreateExtensionStmt is here on purpose:
# in a READ ONLY transaction it fails anyway, and in write mode the extension name is checked
# against ALLOWED_EXTENSIONS (see query_validator).
WRITE_STMT_TYPES: set[type] = {InsertStmt, UpdateStmt, DeleteStmt, CreateExtensionStmt}

# Note: VACUUM/ANALYZE (VacuumStmt) are intentionally NOT allowed in any mode — they write
# to disk and cannot run inside the executor's wrapped transaction block. They are rejected
# with StatementTypeNotAllowedError rather than failing later at execution time.
